# Restart webpack-watcher or webpack-dev-server if you make changes here
paths:
  src_path: app/javascript
  config_path: config/webpack
  node_modules_path: node_modules
  dist_dir: packs
  dist_path: public/packs
